.TH "AbilityActivationKey" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbilityActivationKey \- The key that will be used to activate this ability 1, 2, 3, 4   

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP : int { \fBAbilityKey1\fP = 0, \fBAbilityKey2\fP, \fBAbilityKey3\fP, \fBAbilityKey4\fP, \fBNone\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
The key that will be used to activate this ability 1, 2, 3, 4  
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAbilityActivationKey::Type\fP : int"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAbilityKey1 \fP\fP
.TP
\fB\fIAbilityKey2 \fP\fP
.TP
\fB\fIAbilityKey3 \fP\fP
.TP
\fB\fIAbilityKey4 \fP\fP
.TP
\fB\fINone \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
