.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/ActorComponents/AbilitiesComponent.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/ActorComponents/AbilitiesComponent.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ActorComponent\&.h'\fP
.br
\fC#include 'Abilities/Ability\&.h'\fP
.br
\fC#include 'Attributes/AttributeComponent\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbilitiesComponent\fP"
.br
.RI "A component allowing the object to use abilities @NOTE: Requires an attribute component to function properly  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
