.TH "ActivationOutcome" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActivationOutcome \- Outcome of attempting to activate this ability   

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ability\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBabilityName\fP"
.br
.ti -1c
.RI "std::string \fBfailReason\fP"
.br
.ti -1c
.RI "bool \fBbWasSuccessful\fP = 0"
.br
.ti -1c
.RI "\fBAbilityActivationKey::Type\fP \fBkeyOfAbility\fP = \fBAbilityActivationKey::None\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Outcome of attempting to activate this ability  
.SH "Member Data Documentation"
.PP 
.SS "std::string ActivationOutcome::abilityName"

.SS "bool ActivationOutcome::bWasSuccessful = 0"

.SS "std::string ActivationOutcome::failReason"

.SS "\fBAbilityActivationKey::Type\fP ActivationOutcome::keyOfAbility = \fBAbilityActivationKey::None\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
