.TH "ApplyDamageOn" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ApplyDamageOn \- Enum used to decided on what to apply damage   

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBEnemiesOnly\fP, \fBPlayerOnly\fP, \fBEnemiesAndPlayer\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enum used to decided on what to apply damage  
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBApplyDamageOn::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEnemiesOnly \fP\fP
.TP
\fB\fIPlayerOnly \fP\fP
.TP
\fB\fIEnemiesAndPlayer \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
