.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Attributes/AttributeTypes.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Attributes/AttributeTypes.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFAttribute\fP"
.br
.RI "Attribute representation  "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBHellwatchAttribute\fP"
.br
.RI "Attribute Type  "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHellwatchAttribute::Type\fP { \fBHellwatchAttribute::Health\fP = 0, \fBHellwatchAttribute::Mana\fP, \fBHellwatchAttribute::Vitality\fP, \fBHellwatchAttribute::Wisdom\fP, \fBHellwatchAttribute::Toughness\fP, \fBHellwatchAttribute::Energy\fP, \fBHellwatchAttribute::None\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
