.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Attributes/AttributeComponent.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Attributes/AttributeComponent.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ActorComponents/ActorComponent\&.h'\fP
.br
\fC#include 'GameFramework/Utils\&.h'\fP
.br
\fC#include 'AttributeTypes\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAttributeComponent\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBASE_REGEN_RATIO\fP   7"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BASE_REGEN_RATIO   7"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
