.TH "CooldownStartPolicy" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CooldownStartPolicy \- When should cooldown start, on start of ability or end of ability   

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBOnAbilityStart\fP, \fBOnAbilityEnd\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
When should cooldown start, on start of ability or end of ability  
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCooldownStartPolicy::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOnAbilityStart \fP\fP
.TP
\fB\fIOnAbilityEnd \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
