.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Actors Directory Reference" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Actors Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBMeshActors\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMeshActor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMeshActor\&.h\fP"
.br
.ti -1c
.RI "file \fBSpriteActor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSpriteActor\&.h\fP"
.br
.in -1c
