.TH "DamageOnCollisionActor" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DamageOnCollisionActor \- Actor to spawn to perform damage on collision   

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DamageOnCollisionActor\&.h>\fP
.PP
Inherits \fBMeshActor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnCollision\fP (b2Body *otherBody) override"
.br
.RI "Deal damage on collision  "
.ti -1c
.RI "void \fBSetDamageAmount\fP (float newAmount)"
.br
.RI "Sets the damage amount  "
.ti -1c
.RI "void \fBSetApplyDamageOn\fP (\fBApplyDamageOn::Type\fP newState)"
.br
.RI "Sets to what we should apply damage  "
.ti -1c
.RI "void \fBSetSpinning\fP (bool bNewState)"
.br
.RI "Specifies whether the actor should spin while moving @NOTE: This does not change the movement direction  "
.ti -1c
.RI "void \fBSetIsPiercing\fP (bool bNewState)"
.br
.RI "Sets the projectile to be piercing, passing through all enemies/players until it hits environment  "
.ti -1c
.RI "virtual void \fBUpdate\fP (float deltaTime) override"
.br
.RI "Update function, called every frame  "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBApplyDamageOn::Type\fP \fBapplyDamageOn\fP = \fBApplyDamageOn::EnemiesOnly\fP"
.br
.ti -1c
.RI "bool \fBbSpinning\fP = false"
.br
.ti -1c
.RI "bool \fBbIsPiercing\fP = false"
.br
.ti -1c
.RI "float \fBdamageAmount\fP = 0\&.f"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Actor to spawn to perform damage on collision  
.SH "Member Function Documentation"
.PP 
.SS "void DamageOnCollisionActor::OnCollision (b2Body * otherBody)\fC [override]\fP, \fC [virtual]\fP"

.PP
Deal damage on collision  
.PP
Reimplemented from \fBWorldObject\fP\&.
.SS "void DamageOnCollisionActor::SetApplyDamageOn (\fBApplyDamageOn::Type\fP newState)\fC [inline]\fP"

.PP
Sets to what we should apply damage  
.SS "void DamageOnCollisionActor::SetDamageAmount (float newAmount)\fC [inline]\fP"

.PP
Sets the damage amount  
.SS "void DamageOnCollisionActor::SetIsPiercing (bool bNewState)\fC [inline]\fP"

.PP
Sets the projectile to be piercing, passing through all enemies/players until it hits environment  
.SS "void DamageOnCollisionActor::SetSpinning (bool bNewState)\fC [inline]\fP"

.PP
Specifies whether the actor should spin while moving @NOTE: This does not change the movement direction  
.SS "void DamageOnCollisionActor::Update (float deltaTime)\fC [override]\fP, \fC [virtual]\fP"

.PP
Update function, called every frame  
.PP
\fBParameters\fP
.RS 4
\fIdeltaTime\fP Float variable for the frame time
.RE
.PP

.PP
Reimplemented from \fBMeshActor\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBApplyDamageOn::Type\fP DamageOnCollisionActor::applyDamageOn = \fBApplyDamageOn::EnemiesOnly\fP\fC [protected]\fP"

.SS "bool DamageOnCollisionActor::bIsPiercing = false\fC [protected]\fP"

.SS "bool DamageOnCollisionActor::bSpinning = false\fC [protected]\fP"

.SS "float DamageOnCollisionActor::damageAmount = 0\&.f\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
