.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Interfaces/Damagable.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Interfaces/Damagable.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIDamagable\fP"
.br
.RI "Interface to be added, when we want the specific class to be able to take damage  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
