.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Abilities/PlayerAbilities/Dash.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Abilities/PlayerAbilities/Dash.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Abilities/Ability\&.h'\fP
.br
\fC#include 'ActorComponents/AbilitiesComponent\&.h'\fP
.br
\fC#include 'GameFramework/Utils\&.h'\fP
.br
\fC#include 'Actors/MeshActors/PlayerCharacter\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDash\fP"
.br
.RI "Applies a force to the player in the mouse direction and makes the player briefly invincible  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
