.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Actors/MeshActors/EnemyDummy.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Actors/MeshActors/EnemyDummy.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Actors/MeshActor\&.h'\fP
.br
\fC#include 'Attributes/AttributeComponent\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemyDummy\fP"
.br
.RI "A dummy enemy class used for testing damage  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
