.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Actors/MeshActors/Enemy.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Actors/MeshActors/Enemy.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Actors/MeshActor\&.h'\fP
.br
\fC#include 'Attributes/AttributeComponent\&.h'\fP
.br
\fC#include 'ActorComponents/CharacterMovementComponent\&.h'\fP
.br
\fC#include 'PlayerCharacter\&.h'\fP
.br
\fC#include 'scene_app\&.h'\fP
.br
\fC#include 'DamageOnCollisionActor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemy\fP"
.br
.RI "A base class for all enemies, implemented as a melee enemy  "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEnemyClass\fP"
.br
.RI "\fBEnemy\fP class enum, used to add multipliers to stats  "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEnemyClass::Type\fP { \fBEnemyClass::HEAVY\fP, \fBEnemyClass::NORMAL\fP, \fBEnemyClass::LIGHT\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
