.TH "EnemyClass" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnemyClass \- \fBEnemy\fP class enum, used to add multipliers to stats   

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBHEAVY\fP, \fBNORMAL\fP, \fBLIGHT\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBEnemy\fP class enum, used to add multipliers to stats  
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBEnemyClass::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHEAVY \fP\fP
.TP
\fB\fINORMAL \fP\fP
.TP
\fB\fILIGHT \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
