.TH "FAttribute" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FAttribute \- Attribute representation   

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AttributeTypes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHellwatchAttribute::Type\fP \fBattributeType\fP"
.br
.ti -1c
.RI "float \fBmaxAmount\fP = 100\&.f"
.br
.ti -1c
.RI "float \fBcurrentAmount\fP = 0\&.f"
.br
.ti -1c
.RI "bool \fBbClampedToZero\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attribute representation  
.SH "Member Data Documentation"
.PP 
.SS "\fBHellwatchAttribute::Type\fP FAttribute::attributeType"

.SS "bool FAttribute::bClampedToZero = true"

.SS "float FAttribute::currentAmount = 0\&.f"

.SS "float FAttribute::maxAmount = 100\&.f"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
