.TH "FCameraShake" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FCameraShake
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scene_app\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "gef::Vector4 \fBmaxOffset\fP = gef::Vector4::kZero"
.br
.ti -1c
.RI "gef::Vector4 \fBminOffset\fP = gef::Vector4::kZero"
.br
.ti -1c
.RI "float \fBlerpAlpha\fP = 0\&.f"
.br
.ti -1c
.RI "float \fBduration\fP = 1\&.f"
.br
.ti -1c
.RI "float \fBintensity\fP = 1\&.f"
.br
.ti -1c
.RI "float \fBcameraShakeStartTime\fP = 0\&.f"
.br
.ti -1c
.RI "bool \fBbMovingForward\fP = true"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool FCameraShake::bMovingForward = true"

.SS "float FCameraShake::cameraShakeStartTime = 0\&.f"

.SS "float FCameraShake::duration = 1\&.f"

.SS "float FCameraShake::intensity = 1\&.f"

.SS "float FCameraShake::lerpAlpha = 0\&.f"

.SS "gef::Vector4 FCameraShake::maxOffset = gef::Vector4::kZero"

.SS "gef::Vector4 FCameraShake::minOffset = gef::Vector4::kZero"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
