.TH "FKeyBindMouse" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FKeyBindMouse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlayerController\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "gef::TouchType \fBclickAction\fP"
.br
.ti -1c
.RI "std::function< void(gef::Vector2)> \fBfunctionBind\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "gef::TouchType FKeyBindMouse::clickAction"

.SS "std::function<void(gef::Vector2)> FKeyBindMouse::functionBind"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
