.TH "FParticleData" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FParticleData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParticleActor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< gef::Texture * > \fBtextures\fP"
.br
.ti -1c
.RI "float \fBstartTime\fP = 0"
.br
.ti -1c
.RI "float \fBduration\fP = 1"
.br
.ti -1c
.RI "float \fBlingerTime\fP = 0\&.25"
.br
.ti -1c
.RI "gef::Vector4 \fBscale\fP = gef::Vector4::kOne"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float FParticleData::duration = 1"

.SS "float FParticleData::lingerTime = 0\&.25"

.SS "gef::Vector4 FParticleData::scale = gef::Vector4::kOne"

.SS "float FParticleData::startTime = 0"

.SS "std::vector<gef::Texture*> FParticleData::textures"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
