.TH "FWaveDefinition" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FWaveDefinition \- A definition for a wave, the max number of spawned enemies and the period of spawning them   

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WaveManager\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBmaxSpawns\fP"
.br
.ti -1c
.RI "float \fBspawnPeriod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A definition for a wave, the max number of spawned enemies and the period of spawning them  
.SH "Member Data Documentation"
.PP 
.SS "uint32_t FWaveDefinition::maxSpawns"

.SS "float FWaveDefinition::spawnPeriod"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
