.TH "HellwatchParticle" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HellwatchParticle
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBExplosion\fP, \fBDeath\fP, \fBDash\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBHellwatchParticle::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIExplosion \fP\fP
.TP
\fB\fIDeath \fP\fP
.TP
\fB\fIDash \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
