.TH "HellwatchAttribute" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HellwatchAttribute \- Attribute Type   

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBHealth\fP = 0, \fBMana\fP, \fBVitality\fP, \fBWisdom\fP, \fBToughness\fP, \fBEnergy\fP, \fBNone\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attribute Type  
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBHellwatchAttribute::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHealth \fP\fP
.TP
\fB\fIMana \fP\fP
.TP
\fB\fIVitality \fP\fP
.TP
\fB\fIWisdom \fP\fP
.TP
\fB\fIToughness \fP\fP
.TP
\fB\fIEnergy \fP\fP
.TP
\fB\fINone \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
