.TH "HellwatchInputAction" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HellwatchInputAction
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBNone\fP = 0, \fBPressed\fP, \fBHeld\fP, \fBReleased\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBHellwatchInputAction::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIPressed \fP\fP
.TP
\fB\fIHeld \fP\fP
.TP
\fB\fIReleased \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
