.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Abilities/PlayerAbilities/IceBolt.cpp" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Abilities/PlayerAbilities/IceBolt.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'IceBolt\&.h'\fP
.br
\fC#include 'scene_app\&.h'\fP
.br
\fC#include 'ActorComponents/AbilitiesComponent\&.h'\fP
.br
\fC#include 'maths/math_utils\&.h'\fP
.br
\fC#include 'Actors/MeshActors/DamageOnCollisionActor\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
