.TH "IDamagable" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IDamagable \- Interface to be added, when we want the specific class to be able to take damage   

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Damagable\&.h>\fP
.PP
Inherited by \fBMeshActor\fP\&.
.SH "Detailed Description"
.PP 
Interface to be added, when we want the specific class to be able to take damage  

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
