.TH "D:/Uni/CMP208/Hellwatch/main_d3d11.cpp" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/main_d3d11.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <platform/d3d11/system/platform_d3d11\&.h>\fP
.br
\fC#include 'scene_app\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int WINAPI \fBWinMain\fP (HINSTANCE hInstance, HINSTANCE hPrevInstance, PSTR pScmdline, int iCmdshow)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned int \fBsceLibcHeapSize\fP = 128*1024*1024"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, PSTR pScmdline, int iCmdshow)"

.SH "Variable Documentation"
.PP 
.SS "unsigned int sceLibcHeapSize = 128*1024*1024"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
