.TH "MainMenu" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainMenu \- Main \fBMenu\fP of the game   

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MainMenu\&.h>\fP
.PP
Inherits \fBMenu\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInit\fP ()"
.br
.RI "Initializes the menu  "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Main \fBMenu\fP of the game  
.SH "Member Function Documentation"
.PP 
.SS "void MainMenu::Init ()\fC [virtual]\fP"

.PP
Initializes the menu  
.PP
Implements \fBMenu\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
