.TH "md__d___uni__c_m_p208__hellwatch__r_e_a_d_m_e" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d___uni__c_m_p208__hellwatch__r_e_a_d_m_e \- Hellwatch 
.PP

.SH "Instructions"
.PP
In Hellwatch, you must ward off the demons\&. Use spells to fight off waves of enemies and upgrade your attributes\&. Survive until wave 10 to fight the boss\&. 
.SS "Controls"
.SS "Keyboard"
.IP "\(bu" 2
WASD for movement
.IP "\(bu" 2
1, 2, 3, 4 for spells
.IP "\(bu" 2
Mouse to aim
.IP "\(bu" 2
Left click or enter key to confirm buttons
.IP "\(bu" 2
W, S, and up, down arrows to navigate menus
.IP "\(bu" 2
+/- keys to change volume
.IP "\(bu" 2
Esc key to pause 
.PP
.SS "Controller"
.IP "\(bu" 2
Left Analog stick for movement
.IP "\(bu" 2
Right Analog stick for aiming
.IP "\(bu" 2
Face buttons to cast spells
.IP "\(bu" 2
Up and Down on D-pad to navigate menus
.IP "\(bu" 2
X button to confirm buttons
.IP "\(bu" 2
Select to pause
.IP "\(bu" 2
Options button inverses y-movement 
.PP
.SS "Attributes"
.IP "\(bu" 2
Wisdom increases your damage
.IP "\(bu" 2
Vitality increases your health and health regen
.IP "\(bu" 2
Toughness reduces the damage taken
.IP "\(bu" 2
Energy increases your max mana and magic regeneration 
.PP
.SS "Abilities"
.IP "\(bu" 2
Ice Bolt - Shoot an ice projectile towards your mouse that deals damage to the first enemy it hits
.IP "\(bu" 2
\fBDash\fP - \fBDash\fP towards the mouse and become briefly invincible
.IP "\(bu" 2
Piercing Strike - Shoot a projectile towards the mouse that deals damage to all enemies in its path
.IP "\(bu" 2
\fBMeteor\fP - Create a large meteor that slowly descends and causes massive damage upon impact to all enemies in the area 
.PP

