.TH "D:/Uni/CMP208/Hellwatch/obj_mesh_loader.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/obj_mesh_loader.h
.SH SYNOPSIS
.br
.PP
\fC#include <gef\&.h>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <maths/vector4\&.h>\fP
.br
\fC#include <maths/vector2\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOBJMeshLoader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgef\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< std::string, gef::Mesh * > \fBMeshMap\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::map<std::string, gef::Mesh*> \fBMeshMap\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
