.TH "D:/Uni/CMP208/Hellwatch/obj_mesh_loader.cpp" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/obj_mesh_loader.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'obj_mesh_loader\&.h'\fP
.br
\fC#include <graphics/mesh\&.h>\fP
.br
\fC#include <graphics/primitive\&.h>\fP
.br
\fC#include <system/platform\&.h>\fP
.br
\fC#include <graphics/model\&.h>\fP
.br
\fC#include <assets/png_loader\&.h>\fP
.br
\fC#include <graphics/texture\&.h>\fP
.br
\fC#include <graphics/image_data\&.h>\fP
.br
\fC#include <system/file\&.h>\fP
.br
\fC#include <system/memory_stream_buffer\&.h>\fP
.br
\fC#include <graphics/material\&.h>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <istream>\fP
.br
\fC#include <cfloat>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <cassert>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBStringEndsWith\fP (std::string const &full_string, std::string const &ending)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool StringEndsWith (std::string const & full_string, std::string const & ending)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
