.TH "OBJMeshLoader" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OBJMeshLoader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <obj_mesh_loader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBLoad\fP (const char *filename, gef::Platform &platform, \fBMeshMap\fP &mesh_map)"
.br
.ti -1c
.RI "const std::string & \fBGetLastError\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "const std::string & OBJMeshLoader::GetLastError ()\fC [inline]\fP"

.SS "bool OBJMeshLoader::Load (const char * filename, gef::Platform & platform, \fBMeshMap\fP & mesh_map)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
