.TH "ParticleManager" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParticleManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBPrepareParticles\fP ()"
.br
.RI "Prepares the particles  "
.ti -1c
.RI "void \fBPlayParticlesAtLocation\fP (\fBHellwatchParticle::Type\fP type, gef::Vector4 location)"
.br
.RI "Plays particles at location  "
.ti -1c
.RI "void \fBPlayParticlesAtLocation\fP (\fBHellwatchParticle::Type\fP type, gef::Vector4 location, float duration)"
.br
.RI "Plays particles at location  "
.ti -1c
.RI "void \fBPlayParticlesAtLocation\fP (\fBHellwatchParticle::Type\fP type, gef::Vector4 location, float duration, float lingerTime)"
.br
.RI "Plays particles at location  "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ParticleManager::Init ()"

.SS "void ParticleManager::PlayParticlesAtLocation (\fBHellwatchParticle::Type\fP type, gef::Vector4 location)"

.PP
Plays particles at location  
.SS "void ParticleManager::PlayParticlesAtLocation (\fBHellwatchParticle::Type\fP type, gef::Vector4 location, float duration)"

.PP
Plays particles at location  
.SS "void ParticleManager::PlayParticlesAtLocation (\fBHellwatchParticle::Type\fP type, gef::Vector4 location, float duration, float lingerTime)"

.PP
Plays particles at location  
.SS "void ParticleManager::PrepareParticles ()"

.PP
Prepares the particles  

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
