.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/GameFramework/ParticleManager.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/GameFramework/ParticleManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'maths/vector4\&.h'\fP
.br
\fC#include 'graphics/texture\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParticleManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBHellwatchParticle\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHellwatchParticle::Type\fP { \fBHellwatchParticle::Explosion\fP, \fBHellwatchParticle::Death\fP, \fBHellwatchParticle::Dash\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
