.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/UserInterface/PauseMenu.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/UserInterface/PauseMenu.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Menu\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPauseMenu\fP"
.br
.RI "Pause \fBMenu\fP to be used in Pause \fBGameState\fP  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
