.TH "PauseMenu" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PauseMenu \- Pause \fBMenu\fP to be used in Pause \fBGameState\fP   

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PauseMenu\&.h>\fP
.PP
Inherits \fBMenu\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInit\fP () override"
.br
.RI "Initializes the menu  "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Pause \fBMenu\fP to be used in Pause \fBGameState\fP  
.SH "Member Function Documentation"
.PP 
.SS "void PauseMenu::Init ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Initializes the menu  
.PP
Implements \fBMenu\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
