.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Actors/MeshActors/PlayerCharacter.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Actors/MeshActors/PlayerCharacter.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Actors/MeshActor\&.h'\fP
.br
\fC#include 'GameFramework/PlayerController\&.h'\fP
.br
\fC#include 'graphics/skinned_mesh_instance\&.h'\fP
.br
\fC#include 'GameFramework/Utils\&.h'\fP
.br
\fC#include 'graphics/sprite\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayerCharacter\fP"
.br
.RI "The class that the player uses during the GameLoop \fBGameState\fP  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
