.TH "D:/Uni/CMP208/Hellwatch/primitive_builder.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/primitive_builder.h
.SH SYNOPSIS
.br
.PP
\fC#include <maths/vector4\&.h>\fP
.br
\fC#include <graphics/material\&.h>\fP
.br
\fC#include <cstddef>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrimitiveBuilder\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgef\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
