.TH "D:/Uni/CMP208/Hellwatch/primitive_builder.cpp" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/primitive_builder.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'primitive_builder\&.h'\fP
.br
\fC#include <graphics/mesh\&.h>\fP
.br
\fC#include <system/platform\&.h>\fP
.br
\fC#include <graphics/primitive\&.h>\fP
.br
\fC#include <maths/math_utils\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "gef::Vector4 \fBCalculateSphereSurfaceNormal\fP (const float radius, const gef::Vector4 &origin, const gef::Vector4 &point)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "gef::Vector4 CalculateSphereSurfaceNormal (const float radius, const gef::Vector4 & origin, const gef::Vector4 & point)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
