.TH "D:/Uni/CMP208/Hellwatch/scene_app.cpp" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/scene_app.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'scene_app\&.h'\fP
.br
\fC#include <system/platform\&.h>\fP
.br
\fC#include <graphics/sprite_renderer\&.h>\fP
.br
\fC#include <graphics/font\&.h>\fP
.br
\fC#include <system/debug_log\&.h>\fP
.br
\fC#include <graphics/renderer_3d\&.h>\fP
.br
\fC#include <maths/math_utils\&.h>\fP
.br
\fC#include 'graphics/sprite\&.h'\fP
.br
\fC#include 'assets/png_loader\&.h'\fP
.br
\fC#include <graphics/image_data\&.h>\fP
.br
\fC#include <audio/audio_manager\&.h>\fP
.br
\fC#include 'input/sony_controller_input_manager\&.h'\fP
.br
\fC#include 'UserInterface/MainMenu\&.h'\fP
.br
\fC#include 'UserInterface/ShopMenu\&.h'\fP
.br
\fC#include 'UserInterface/PauseMenu\&.h'\fP
.br
\fC#include 'UserInterface/GameEndMenu\&.h'\fP
.br
\fC#include 'Actors/MeshActors/PlayerCharacter\&.h'\fP
.br
\fC#include 'Actors/SpriteActor\&.h'\fP
.br
\fC#include 'Actors/MeshActors/Enemy\&.h'\fP
.br
\fC#include 'Actors/MeshActors/RangedEnemy\&.h'\fP
.br
\fC#include 'Actors/MeshActor\&.h'\fP
.br
\fC#include 'GameFramework/WaveManager\&.h'\fP
.br
\fC#include 'GameFramework/PlayerController\&.h'\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'GameFramework/ParticleManager\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
