.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/UserInterface/ShopMenu.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/UserInterface/ShopMenu.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Menu\&.h'\fP
.br
\fC#include 'Attributes/AttributeTypes\&.h'\fP
.br
\fC#include 'Abilities/Ability\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBShopMenu\fP"
.br
.RI "Shop menu to be used in Shop \fBGameState\fP  "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUPGRADE_COST_FORMULA\fP(amountOfUpgrades)   (upgradeCost * amountOfUpgrades) * 0\&.5 + 5"
.br
.ti -1c
.RI "#define \fBMAX_COST\fP   3000\&.f"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_COST   3000\&.f"

.SS "#define UPGRADE_COST_FORMULA(amountOfUpgrades)   (upgradeCost * amountOfUpgrades) * 0\&.5 + 5"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
