.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Actors/SpriteActor.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Actors/SpriteActor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'GameFramework/WorldObject\&.h'\fP
.br
\fC#include 'graphics/sprite\&.h'\fP
.br
\fC#include 'graphics/texture\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpriteActor\fP"
.br
.RI "An object that has a sprite  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
