.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/Actors/SpriteActor.cpp" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/Actors/SpriteActor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'SpriteActor\&.h'\fP
.br
\fC#include 'graphics/sprite_renderer\&.h'\fP
.br
\fC#include <scene_app\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
