.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/GameFramework/WaveManager.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/GameFramework/WaveManager.h
.SH SYNOPSIS
.br
.PP
\fC#include 'GameFramework/Utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFWaveDefinition\fP"
.br
.RI "A definition for a wave, the max number of spawned enemies and the period of spawning them  "
.ti -1c
.RI "class \fBWaveManager\fP"
.br
.RI "Manages the spawning of enemies and tracking the progress of waves  "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_WAVE_FORMULA\fP   (currentWave + currentWave * 0\&.5) * 5"
.br
.ti -1c
.RI "#define \fBSPAWN_PERIOD_AFTER_WAVE_DEFINITIONS\fP   1\&.f"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SPAWN_PERIOD_AFTER_WAVE_DEFINITIONS   1\&.f"

.SS "#define USE_WAVE_FORMULA   (currentWave + currentWave * 0\&.5) * 5"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
