.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/GameFramework/WaveManager.cpp" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/GameFramework/WaveManager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'WaveManager\&.h'\fP
.br
\fC#include <random>\fP
.br
\fC#include 'Actors/MeshActors/Enemy\&.h'\fP
.br
\fC#include 'Actors/MeshActors/RangedEnemy\&.h'\fP
.br
\fC#include 'Actors/MeshActors/Boss\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
