.TH "D:/Uni/CMP208/Hellwatch/build/vs2017/GameFramework/WorldObject.h" 3 "Thu Apr 27 2023" "Hellwatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Uni/CMP208/Hellwatch/build/vs2017/GameFramework/WorldObject.h
.SH SYNOPSIS
.br
.PP
\fC#include <maths/Matrix44\&.h>\fP
.br
\fC#include <maths/quaternion\&.h>\fP
.br
\fC#include 'Utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWorldObject\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hellwatch from the source code\&.
